export default {
  categories: {
    correctness: 'error',
    style: 'warn',
    suspicious: 'error',
  },
  env: {
    builtin: true,
    node: true,
  },
  globals: {
    Bun: 'readonly',
  },
  ignorePatterns: ['node_modules', 'dist', '.omo', 'bun.lock', 'test/fixtures', 'scripts/config'],
  jsPlugins: [
    {
      name: 'perfectionist',
      specifier: 'eslint-plugin-perfectionist',
    },
    {
      name: 'style',
      specifier: '@stylistic/eslint-plugin',
    },
  ],
  overrides: [
    {
      files: ['**/*.ts', '**/*.mts', '**/*.cts'],
      rules: {
        'constructor-super': 'off',
        'getter-return': 'off',
        'no-class-assign': 'off',
        'no-const-assign': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-keys': 'off',
        'no-func-assign': 'off',
        'no-import-assign': 'off',
        'no-new-native-nonconstructor': 'off',
        'no-obj-calls': 'off',
        'no-redeclare': 'off',
        'no-setter-return': 'off',
        'no-this-before-super': 'off',
        'no-undef': 'off',
        'no-unreachable': 'off',
        'no-unsafe-negation': 'off',
        'no-var': 'error',
        'no-with': 'off',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
      },
    },
    {
      files: ['**/bun-test.d.ts'],
      rules: {
        'arrow-body-style': 'off',
        curly: 'off',
        'no-nested-ternary': 'off',
        'typescript/consistent-type-assertions': 'off',
        'typescript/consistent-type-imports': 'off',
      },
    },
    {
      files: [
        'scripts/**/*',
        'test/**/*',
        '**/tests/**/*',
        '**/*.test.ts',
        '**/*-test.ts',
        '**/*-test-layers.ts',
        'vite.*.ts',
        'vitest.config.*',
      ],
      rules: {
        'import/no-nodejs-modules': 'off',
        'no-useless-assignment': 'off',
      },
    },
  ],
  plugins: ['eslint', 'import', 'oxc', 'typescript', 'unicorn'],
  rules: {
    'arrow-body-style': 'off',
    'constructor-super': 'error',
    curly: ['error', 'all'],
    'eslint/id-length': ['error', { min: 2, properties: 'never' }],
    'eslint/init-declarations': 'off',
    'eslint/max-statements': 'off',
    'eslint/no-magic-numbers': 'off',
    'eslint/no-ternary': 'off',
    'eslint/sort-imports': 'off',
    'eslint/func-names': 'off',
    'eslint/max-params': 'off',
    'eslint/one-var': 'off',
    'eslint/no-continue': 'off',
    'eslint/no-implicit-coercion': 'off',
    'eslint/no-template-curly-in-string': 'off',
    'eslint/prefer-destructuring': 'off',
    'eslint/prefer-named-capture-group': 'off',
    'eslint/sort-keys': 'off',
    'for-direction': 'error',
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'getter-return': 'error',
    'import/consistent-type-specifier-style': 'off',
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-named-export': 'off',
    'import/no-anonymous-default-export': 'off',
    'import/no-namespace': 'off',
    'import/no-nodejs-modules': 'off',
    'import/prefer-default-export': 'off',
    'new-cap': 'off',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'off',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-nested-ternary': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow': 'off',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unassigned-vars': 'error',
    'no-undef': 'error',
    'no-underscore-dangle': ['error', { allow: ['_tag', '_op', '_id'] }],
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-useless-assignment': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'perfectionist/sort-exports': [
      'error',
      {
        order: 'asc',
        type: 'natural',
      },
    ],
    'perfectionist/sort-imports': [
      'error',
      {
        customGroups: [],
        groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
        internalPattern: ['^@/.+', '^~/.+', '^#.+'],
        newlinesBetween: 1,
      },
    ],
    'perfectionist/sort-named-exports': [
      'error',
      {
        order: 'asc',
        type: 'natural',
      },
    ],
    'perfectionist/sort-named-imports': [
      'error',
      {
        order: 'asc',
        type: 'natural',
      },
    ],
    'preserve-caught-error': 'error',
    'require-yield': 'error',
    'style/max-len': 'off',
    'style/padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: '*', next: ['if', 'for', 'while', 'switch', 'try'] },
      { blankLine: 'always', prev: ['if', 'for', 'while', 'switch', 'try', 'block-like'], next: '*' },
      { blankLine: 'always', prev: ['const', 'let'], next: '*' },
      { blankLine: 'any', prev: ['const', 'let'], next: ['const', 'let'] },
      { blankLine: 'always', prev: '*', next: 'return' },
    ],
    'typescript/ban-ts-comment': 'error',
    'typescript/consistent-type-assertions': [
      'error',
      {
        assertionStyle: 'never',
      },
    ],
    'typescript/consistent-type-imports': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',
    'unicorn/filename-case': [
      'error',
      {
        case: 'kebabCase',
        ignore: ['^__root$', '^vite-env$', String.raw`^routeTree\.gen$`],
      },
    ],
    'unicorn/custom-error-definition': 'off',
    'unicorn/max-nested-calls': 'off',
    'unicorn/no-null': 'off',
    'unicorn/prefer-native-coercion-functions': 'off',
    'unicorn/numeric-separators-style': 'off',
    'unicorn/text-encoding-identifier-case': 'off',
    'use-isnan': 'error',
    'valid-typeof': 'error',
  },
}
